# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build.py - do not edit manually
import os, fnmatch

block_cipher = None

STRIP_DLLS = [
    "msvcp140.dll","msvcp140_1.dll","msvcp140_2.dll",
    "vcruntime140.dll","vcruntime140_1.dll",
    "api-ms-win-*.dll","ext-ms-win-*.dll",
    "kernel32.dll","kernelbase.dll","user32.dll","gdi32.dll",
    "advapi32.dll","ole32.dll","oleaut32.dll","shell32.dll",
    "ntdll.dll","ws2_32.dll","rpcrt4.dll","secur32.dll",
    "crypt32.dll","bcrypt.dll","ucrtbase.dll","combase.dll",
]
def _strip(name):
    n = os.path.basename(name).lower()
    return any(fnmatch.fnmatch(n, p.lower()) for p in STRIP_DLLS)

a = Analysis(
    ["main.py"],
    pathex=['E:\\AurumOS_Client', 'E:\\AurumOS_Client\\.venv\\Lib\\site-packages', 'E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32', 'E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib'],
    binaries=[
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\mmapfile.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\odbc.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\perfmon.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\servicemanager.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\timer.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32api.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32clipboard.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32console.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32cred.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32crypt.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32event.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32evtlog.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32file.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32gui.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32help.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32inet.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32job.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32lz.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32net.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32pdh.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32pipe.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32print.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32process.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32profile.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32ras.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32security.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32service.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32trace.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32transaction.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32ts.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\win32wnet.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\_win32sysloader.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\_winxptheme.pyd', "win32"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\pywin32_system32\\pythoncom312.dll', "."),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\pywin32_system32\\pywintypes312.dll', "."),
        ('C:\\Windows\\System32\\winspool.drv', "."),

    ],
    datas=[
        ("ui",    "ui"),
        ("fonts", "fonts"),
        ("core",  "core"),
        ("network", "network"),
        ("E:/AurumOS_Client/.venv/Lib/site-packages/serial", "serial"),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\afxres.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\commctrl.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\mmsystem.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\netbios.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\ntsecuritycon.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\pywin32_bootstrap.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\pywin32_testutil.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\pywintypes.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\rasutil.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\regcheck.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\regutil.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\sspi.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\sspicon.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win2kras.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32con.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32cryptcon.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32evtlogutil.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32gui_struct.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32inetcon.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32netcon.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32pdhquery.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32pdhutil.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32rcparser.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32serviceutil.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32timezone.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32traceutil.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\win32verstamp.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\winerror.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\winioctlcon.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\winnt.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\winperf.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\winxptheme.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\win32\\lib\\_win32verstamp_pywin32ctypes.py', 'win32\\lib'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\webview\\lib\\runtimes\\win-arm64\\native\\WebView2Loader.dll', 'webview\\lib\\runtimes\\win-arm64\\native'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\webview\\lib\\runtimes\\win-x64\\native\\WebView2Loader.dll', 'webview\\lib\\runtimes\\win-x64\\native'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\webview\\lib\\runtimes\\win-x86\\native\\WebView2Loader.dll', 'webview\\lib\\runtimes\\win-x86\\native'),
        ('E:\\AurumOS_Client\\.venv\\Lib\\site-packages\\clr_loader\\ffi\\dlls\\amd64\\ClrLoader.dll', "pythonnet/runtime"),
    ],
    hiddenimports=[
        "pythonnet","clr_loader","clr_loader.netfx","clr_loader.hostfxr","clr_loader.ffi", # ── FIXED: CLR host for pywebview winforms
        "requests", "urllib3", "charset_normalizer", "idna", # ── FIXED: FORCE INJECTED REQUESTS BINARIES
        "updater","subscription_manager","database","database.db_manager","core","core.tag_engine","sync_engine","network_client",
        "serial","serial.tools","serial.tools.list_ports","serial.serialutil",
        "serial.serialwin32","serial.win32","serial.win32con","serial.win32file",
        "serial.win32pipe","serial.urlhandler","serial.urlhandler.protocol_hwgrep",
        "serial.urlhandler.protocol_com","serial.urlhandler.protocol_rfc2217",
        "webview","webview.http","webview.util","webview.guilib",
        "webview.platforms","webview.platforms.edgechromium","webview.platforms.winforms",
        "http","http.server","http.client","http.cookies","http.cookiejar",
        "wsgiref","wsgiref.simple_server","wsgiref.util","wsgiref.handlers",
        "wsgiref.headers","wsgiref.validate",
        "urllib","urllib.parse","urllib.request","urllib.error",
        "urllib.response","urllib.robotparser",
        "email","email.parser","email.message","email.feedparser",
        "email.policy","email.header","email.charset","email.encoders","email.utils",
        "html","html.parser","socket","ssl","socketserver",
        "threading","queue","io","copy","inspect","functools","contextlib",
        "typing","enum","weakref","struct","string","codecs","platform",
        "pathlib","uuid","hashlib","base64","zlib","marshal",
        "sqlite3","json","logging",
        "encodings","encodings.utf_8","encodings.ascii","encodings.latin_1","encodings.idna",
        "win32api","win32con","win32print","win32gui","win32security","win32file",
        "win32process","win32event","win32clipboard","win32cred","win32crypt",
        "win32inet","win32job","win32pipe","win32ts","pywintypes",
        "qrcode","qrcode.image.base","qrcode.image.pil",
        "PIL","PIL._imaging","PIL.ImageDraw","PIL.ImageFont","PIL.ImageWin",
        "PIL.Image","PIL.ImageColor",
        # ── FIXED: ALL local project modules (hidden from PyInstaller
        #    because main.py is obfuscated to marshal before the build step) ──
        "sse_listener",
        "network","network.discovery","network.brain_server","network.brain_client",
        "network.brain_guard","network.connection_store","network.handshake","network.hardware_map",
        "database.bastion_ai","database.bastion_report","database.aurum_health",
        "core.bastion_sync","core.ai_support","core.io_safety","core.security_lock","core.print_bridge",
    ],
    hookspath=["."],
    hooksconfig={},
    runtime_hooks=[
    "rthook_fix_http.py",
    "rthook_serial.py",
    "rthook_pythonnet.py",
],
    excludes=["tkinter","matplotlib","numpy","pandas","scipy","test"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

before = len(a.binaries)
a.binaries = [(n,p,k) for (n,p,k) in a.binaries if not _strip(n)]
print(f"[SPEC] Stripped {before - len(a.binaries)} system DLLs")

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz, a.scripts, [],
    name="AurumOS",
    icon="AurumOS.ico" if os.path.exists("AurumOS.ico") else None,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=["win32api.pyd","win32print.pyd","win32gui.pyd",
                 "pywintypes*.dll","pythoncom*.dll","winspool.drv","WebView2Loader.dll",
                 "Python.Runtime.dll","ClrLoader.dll","Python.Runtime.deps.json",
                 "python3.dll","python312.dll"],
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Keep all deps inside an _internal/ subfolder for a CLEAN client folder:
    # the top level shows only AurumOS.exe (+ the app's runtime data dirs). The
    # pythonnet "Failed to resolve ...Loader.Initialize" crash is handled by
    # rthook_pythonnet.py, which puts _internal/ and _internal/pythonnet/runtime
    # on the DLL search path, discovers the .NET runtime dirs, and initializes
    # the CLR at startup (coreclr first, netfx fallback) - so we no longer need
    # to flatten the bundle to make pythonnet resolve.
    contents_directory="_internal",
)

# ── ONEDIR COLLECT ──────────────────────────────────────────────────────
# Using ONEDIR (instead of a single bundled onefile) is the permanent fix
# for "the EXE takes too long to open". A onefile build extracts ALL of its
# binaries + the WebView2 runtimes + bundled data to a temp _MEIxxxx folder
# on EVERY launch - for an app this size that extraction alone costs several
# seconds before the window even appears. ONEDIR keeps the EXE and its
# dependencies side-by-side in dist/AurumOS/, so there is no per-launch
# extraction: the app starts as fast as the OS can load the binary.
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=["win32api.pyd","win32print.pyd","win32gui.pyd",
                 "pywintypes*.dll","pythoncom*.dll","winspool.drv","WebView2Loader.dll",
                 "Python.Runtime.dll","ClrLoader.dll","Python.Runtime.deps.json",
                 "python3.dll","python312.dll"],
    name="AurumOS",
)
